<?php
/**
 * Created by CPA SIMUSANTE.
 * User: user
 * Date: 29/06/15
 * Time: 14:46
 */

namespace UJM\ExoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InteractionTimedQcmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InteractionTimedQcmRepository extends EntityRepository
{

    /**
     * Get InteractiontimedQcm linked with an interaction
     *
     * @access public
     *
     * @param integer $interactionId id Interaction
     *
     * Return array[InteractionTimedQcm]
     */
    public function getInteractionTimedQcm($interactionId)
    {

        $qb = $this->createQueryBuilder('itimedQcm');
        $qb->join('itimedQcm.interaction', 'i')
           ->where($qb->expr()->in('i.id', $interactionId));
        return $qb->getQuery()->getResult();
    }
}