<?php

/**
 * Created by CPA SIMUSANTE.
 * User: user
 * Date: 07/07/15
 * Time: 12:10
 */

namespace UJM\ExoBundle\Entity;

/**
 * TimedQcmChoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimedQcmChoiceRepository
{
    /**
     * right choice for a TimedQcm interaction
     *
     * @access public
     *
     * @param  integer  $interactionId id InteractionTimedQcm
     *
     * Return array[TimedQcmChoice]
     */
    public function getRightChoice($interactionId)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->join('c.interactionTimedQcm', 'itimedQcm')
            ->where($qb->expr()->in('itimedQcm.id', $interactionId))
            ->andWhere('c.rightResponse = 1');

        return $qb->getQuery()->getResult();
    }
}
