<?php
/**
 * Created by CPA SIMUSANTE.
 * User: user
 * Date: 29/06/15
 * Time: 14:50
 */

namespace UJM\ExoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeTimedQcmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTimedQcmRepository extends EntityRepository
{

}